services:
  homeinventory:
    container_name: homeinventory
    image: homeinventory
    ports:
      - 5066:8080
    build:
      context: .
      dockerfile: HomeInventory/Dockerfile
  homeinvdb:
    image: postgres:13               
    environment:
      - POSTGRES_USER=sqladmin
      - POSTGRES_PASSWORD=Passw0rd!123
      - POSTGRES_DB=homeinventorydb
    ports:
      - "5433:5432"                   
    volumes:
      - db-data:/var/lib/postgresql/data 
  homeinvapigateway:
    image: homeinvapigateway
    environment:
      - ADDITIONAL_INFO=Compose
    ports:
      - 5298:8080
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
  testbox:
    image: ubuntu
    container_name: testbox
    command: sleep 3600    
volumes:
  db-data:
    driver: local