import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">

        <body className="h-screen w-screen bg-gray-100 flex flex-row">
        {/* Sol tarafdaki menü */}
        <nav className="w-64 bg-white shadow-md p-4 flex flex-col gap-4">
            <div className="text-2xl font-bold mb-6">Home Inventory</div>
            <Link href="/HomeInventory/Inventory" className="text-gray-700 hover:bg-gray-200 rounded-md py-2 px-3">
                Inventory
            </Link>
            <Link href="/HomeInventory/Owner" className="text-gray-700 hover:bg-gray-200 rounded-md py-2 px-3">
                Owner
            </Link>
            {/* İsterseniz burada daha fazla link ekleyebilirsiniz */}
        </nav>

        {/* Sağ tarafta içerik alanı */}
        <main className="flex-1 p-8 overflow-auto">
            {children}
        </main>
        </body>
        </html>
    );
}
